name: Check gateway.yml for missing RPCs
on:
  pull_request:
    types: [opened, synchronize]
    branches: [main]
jobs:
  gateway-yml-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Check gateway.yml for missing RPCs
        run: ./scripts/gateway-yml-check.sh
permissions:
  contents: read
